products:
    pattern: /products
    defaults: { _controller: MinicoSilverBundle:Products:index }
products_new:
    pattern: /products/new
    defaults: { _controller: MinicoSilverBundle:Products:new }
products_create:
    pattern: /products/create
    defaults: { _controller: MinicoSilverBundle:Products:create }
products_show:
    pattern: /products/show/{id}
    defaults: { _controller: MinicoSilverBundle:Products:show }
    requirements: { _method: get }
products_delete:
    pattern: /products/delete/{id}
    defaults: { _controller: MinicoSilverBundle:Products:delete }
    requirements: { _method: delete }
products_edit:
    pattern: /products/edit/{id}
    defaults: { _controller: MinicoSilverBundle:Products:edit }
    requirements: { _method: get }
products_update:
    pattern: /products/update/{id}
    defaults: { _controller: MinicoSilverBundle:Products:update }
    requirements: { _method: put }