<?php

namespace Minico\SilverBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuppliersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuppliersRepository extends EntityRepository
{
}
