<?php

namespace Minico\SilverBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WithdrawlsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawlsRepository extends EntityRepository
{
}
